import type { LLMAuthMode } from '../llm/router/types'
import type { ProviderAccessMode, ProviderID, ProviderRegistryEntry, ProviderRegistryID } from './types'

export const PROVIDER_REGISTRY: ProviderRegistryEntry[] = [
  {
    id: 'openai',
    name: 'OpenAI API',
    accessModes: ['api_access', 'gateway_virtual_key'],
    accessLabel: 'API access or local gateway virtual-key access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://platform.openai.com/api-keys',
    officialSourceUrl: 'https://developers.openai.com/api/reference/resources/models/methods/list',
    discoveryStrategy: 'openai_compatible_models',
    status: 'active_configurable',
    classification: 'gateway_configurable_openai_compatible',
    liveCallable: true,
    executableProviderId: 'openai',
    gatewayProfile: {
      kind: 'openai_compatible',
      defaultBaseUrl: 'https://api.openai.com/v1',
      note: 'Direct router client exists; Bifrost/local gateway can use OpenAI-compatible routing.',
    },
    fallbackModels: ['gpt-5.1', 'gpt-5', 'gpt-5-mini', 'gpt-5-nano', 'gpt-4.1'],
    registryInclusionNote: 'Executable direct provider plus gateway-compatible Provider Center row.',
    evidenceNote: 'Official Models API supports model listing.',
  },
  {
    id: 'openai_codex',
    name: 'OpenAI Codex Auth Token',
    accessModes: ['local_tool_session'],
    accessLabel: 'OpenAI Codex local auth token/session',
    authLabel: 'Existing OpenAI Codex authentication',
    setupUrl: 'https://developers.openai.com/codex',
    officialSourceUrl: 'https://developers.openai.com/codex',
    discoveryStrategy: 'static_fallback_only',
    status: 'active_configurable',
    classification: 'local_tool_session',
    liveCallable: true,
    executableProviderId: 'codex',
    fallbackModels: ['gpt-5.1', 'gpt-5', 'gpt-5-mini', 'gpt-5-nano'],
    registryInclusionNote: 'Maps to the local Codex CLI authenticated session without accepting raw OpenAI browser/session credentials.',
    evidenceNote: 'SkillMall delegates authentication to the local Codex CLI session.',
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude API',
    accessModes: ['api_access'],
    accessLabel: 'API access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://console.anthropic.com/settings/keys',
    officialSourceUrl: 'https://platform.claude.com/docs/en/api/models/list',
    discoveryStrategy: 'official_provider_models',
    status: 'active_configurable',
    classification: 'active_configurable',
    liveCallable: true,
    executableProviderId: 'anthropic',
    fallbackModels: ['claude-sonnet-4-20250514', 'claude-opus-4-1-20250805'],
    registryInclusionNote: 'Executable direct provider with provider-specific model-list semantics.',
    evidenceNote: 'Official Claude API models endpoint is provider-specific, not generic /v1/models.',
  },
  {
    id: 'claude_code',
    name: 'Claude Code CLI Auth Token',
    accessModes: ['local_tool_session'],
    accessLabel: 'Local tool session',
    authLabel: 'Existing Claude Code CLI authentication',
    setupUrl: 'https://claude.ai/code',
    officialSourceUrl: 'https://claude.ai/code',
    discoveryStrategy: 'static_fallback_only',
    status: 'status_only',
    classification: 'local_tool_session',
    liveCallable: true,
    executableProviderId: 'claude-code',
    fallbackModels: ['claude-sonnet-4-6', 'claude-opus-4-7', 'claude-haiku-4-5-20251001'],
    registryInclusionNote: 'Maps to the existing claude-code executable client without accepting raw Claude credentials.',
    evidenceNote: 'SkillMall delegates authentication to the local Claude Code CLI session.',
  },
  {
    id: 'gemini',
    name: 'Google Gemini API',
    accessModes: ['api_access'],
    accessLabel: 'API access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://aistudio.google.com/app/apikey',
    officialSourceUrl: 'https://ai.google.dev/api/models',
    discoveryStrategy: 'official_provider_models',
    status: 'active_configurable',
    classification: 'active_configurable',
    liveCallable: true,
    executableProviderId: 'gemini',
    fallbackModels: ['gemini-2.0-flash-exp', 'gemini-1.5-pro'],
    registryInclusionNote: 'Executable direct provider with Google AI model-list semantics.',
    evidenceNote: 'Google AI model APIs are official provider-specific discovery, not an OpenAI-compatible endpoint.',
  },
  {
    id: 'groq',
    name: 'Groq',
    accessModes: ['api_access', 'gateway_virtual_key'],
    accessLabel: 'API access or local gateway virtual-key access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://console.groq.com/keys',
    officialSourceUrl: 'https://console.groq.com/docs/api-reference',
    discoveryStrategy: 'openai_compatible_models',
    status: 'active_configurable',
    classification: 'gateway_configurable_openai_compatible',
    liveCallable: true,
    executableProviderId: 'groq',
    gatewayProfile: {
      kind: 'openai_compatible',
      defaultBaseUrl: 'https://api.groq.com/openai/v1',
      note: 'Existing direct client uses an OpenAI-compatible Groq base URL.',
    },
    fallbackModels: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant'],
    registryInclusionNote: 'Executable direct provider plus OpenAI-compatible gateway profile.',
    evidenceNote: 'Groq API reference exposes OpenAI-compatible model listing.',
  },
  {
    id: 'ollama',
    name: 'Ollama',
    accessModes: ['local_runtime'],
    accessLabel: 'Local runtime',
    authLabel: 'No credential required for default local runtime',
    setupUrl: 'https://ollama.com',
    officialSourceUrl: 'https://github.com/ollama/ollama/blob/main/docs/api.md',
    discoveryStrategy: 'local_runtime_models',
    status: 'active_configurable',
    classification: 'local_runtime',
    liveCallable: true,
    executableProviderId: 'ollama',
    gatewayProfile: {
      kind: 'openai_compatible',
      defaultBaseUrl: 'http://localhost:11434/v1',
      note: 'Local runtime can expose OpenAI-compatible chat execution, but model discovery uses Ollama local runtime tags.',
    },
    fallbackModels: ['llama3.1', 'mistral', 'codellama'],
    registryInclusionNote: 'Executable local runtime provider.',
    evidenceNote: 'Local runtime model availability is environment-specific.',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    accessModes: ['api_access', 'gateway_virtual_key'],
    accessLabel: 'API access or local gateway virtual-key access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://openrouter.ai/keys',
    officialSourceUrl: 'https://openrouter.ai/docs/api/api-reference/models/get-models',
    discoveryStrategy: 'openai_compatible_models',
    status: 'active_configurable',
    classification: 'gateway_configurable_openai_compatible',
    liveCallable: true,
    gatewayProfile: {
      kind: 'openai_compatible',
      defaultBaseUrl: 'https://openrouter.ai/api/v1',
      note: 'Registry-only row until a direct executable adapter is added.',
    },
    fallbackModels: ['openai/gpt-5', 'anthropic/claude-sonnet-4', 'google/gemini-pro'],
    registryInclusionNote: 'Broad registry row; no current direct ProviderID mapping.',
    evidenceNote: 'Official OpenRouter models endpoint is available through its API reference.',
  },
  {
    id: 'alibaba_dashscope_qwen',
    name: 'Alibaba Cloud Model Studio / DashScope / Qwen',
    accessModes: ['api_access', 'gateway_virtual_key'],
    accessLabel: 'API access or configured OpenAI-compatible access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://www.alibabacloud.com/help/doc-detail/3016809.html',
    officialSourceUrl: 'https://www.alibabacloud.com/help/doc-detail/3016809.html',
    discoveryStrategy: 'source_backed_static_models',
    status: 'active_configurable',
    classification: 'gateway_configurable_openai_compatible',
    liveCallable: true,
    gatewayProfile: {
      kind: 'openai_compatible',
      requiresUserEndpoint: true,
      note: 'Configured regional DashScope-compatible endpoint required; model discovery uses source-backed static/manual labels until a durable official model-list endpoint is proven.',
    },
    fallbackModels: ['qwen-plus', 'qwen-max', 'qwen-turbo'],
    registryInclusionNote: 'Broad registry row; execution is through a generic configured OpenAI-compatible target, not a new ProviderID.',
    evidenceNote: 'Official Alibaba/DashScope docs prove API-key execution examples; no durable model-list endpoint is assumed.',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face Inference Providers',
    accessModes: ['api_access'],
    accessLabel: 'API access',
    authLabel: 'Environment variable token reference',
    setupUrl: 'https://huggingface.co/settings/tokens',
    officialSourceUrl: 'https://huggingface.co/docs/inference-providers/main/hub-api',
    discoveryStrategy: 'official_provider_models',
    status: 'active_configurable',
    classification: 'active_configurable',
    liveCallable: true,
    fallbackModels: [],
    registryInclusionNote: 'Broad registry row; no current direct ProviderID mapping.',
    evidenceNote: 'Hub API/provider mapping needs provider-specific discovery behavior.',
  },
  {
    id: 'zai',
    name: 'Z.AI',
    accessModes: ['api_access', 'gateway_virtual_key'],
    accessLabel: 'API access or configured OpenAI-compatible access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://docs.z.ai/api-reference/',
    officialSourceUrl: 'https://docs.z.ai/api-reference/',
    discoveryStrategy: 'source_backed_static_models',
    status: 'active_configurable',
    classification: 'gateway_configurable_openai_compatible',
    liveCallable: true,
    gatewayProfile: {
      kind: 'openai_compatible',
      requiresUserEndpoint: true,
      note: 'Configured Z.AI-compatible endpoint required; model discovery uses source-backed static/manual labels until a durable official model-list endpoint is proven.',
    },
    fallbackModels: ['glm-5.1', 'glm-4.6'],
    registryInclusionNote: 'Broad registry row; execution is through a generic configured OpenAI-compatible target, not a new ProviderID.',
    evidenceNote: 'Official Z.AI docs prove bearer/API execution examples; no durable model-list endpoint is assumed.',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    accessModes: ['api_access', 'gateway_virtual_key'],
    accessLabel: 'API access or local gateway virtual-key access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://platform.minimax.io',
    officialSourceUrl: 'https://platform.minimax.io/docs/api-reference/models/openai/list-models',
    discoveryStrategy: 'openai_compatible_models',
    status: 'active_configurable',
    classification: 'gateway_configurable_openai_compatible',
    liveCallable: true,
    gatewayProfile: {
      kind: 'openai_compatible',
      note: 'Registry-only OpenAI-compatible row until a direct executable adapter is added.',
    },
    fallbackModels: [],
    registryInclusionNote: 'Broad registry row; no current direct ProviderID mapping.',
    evidenceNote: 'Official MiniMax OpenAI-compatible model-list endpoint is recorded in the plan.',
  },
  {
    id: 'kimi_moonshot',
    name: 'Kimi / Moonshot AI',
    accessModes: ['api_access', 'gateway_virtual_key'],
    accessLabel: 'API access or local gateway virtual-key access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://platform.moonshot.ai/console/api-keys',
    officialSourceUrl: 'https://platform.moonshot.ai/docs',
    discoveryStrategy: 'openai_compatible_models',
    status: 'active_configurable',
    classification: 'gateway_configurable_openai_compatible',
    liveCallable: true,
    gatewayProfile: {
      kind: 'openai_compatible',
      defaultBaseUrl: 'https://api.moonshot.ai/v1',
      note: 'Registry-only OpenAI-compatible row until a direct executable adapter is added.',
    },
    fallbackModels: [],
    registryInclusionNote: 'Broad registry row; no current direct ProviderID mapping.',
    evidenceNote: 'Classified as gateway-compatible by the approved T903 contract.',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    accessModes: ['api_access', 'gateway_virtual_key'],
    accessLabel: 'API access or local gateway virtual-key access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://platform.deepseek.com/api_keys',
    officialSourceUrl: 'https://api-docs.deepseek.com/api/list-models',
    discoveryStrategy: 'openai_compatible_models',
    status: 'active_configurable',
    classification: 'gateway_configurable_openai_compatible',
    liveCallable: true,
    gatewayProfile: {
      kind: 'openai_compatible',
      defaultBaseUrl: 'https://api.deepseek.com',
      note: 'Registry-only OpenAI-compatible row until a direct executable adapter is added.',
    },
    fallbackModels: [],
    registryInclusionNote: 'Broad registry row; no current direct ProviderID mapping.',
    evidenceNote: 'Official DeepSeek model-list endpoint is recorded in the plan.',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    accessModes: ['api_access', 'gateway_virtual_key'],
    accessLabel: 'API access or local gateway virtual-key access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://console.mistral.ai',
    officialSourceUrl: 'https://docs.mistral.ai/api/endpoint/models',
    discoveryStrategy: 'openai_compatible_models',
    status: 'active_configurable',
    classification: 'gateway_configurable_openai_compatible',
    liveCallable: true,
    gatewayProfile: {
      kind: 'openai_compatible',
      defaultBaseUrl: 'https://api.mistral.ai/v1',
      note: 'Registry-only OpenAI-compatible row until a direct executable adapter is added.',
    },
    fallbackModels: [],
    registryInclusionNote: 'Broad registry row; no current direct ProviderID mapping.',
    evidenceNote: 'Official Mistral model-list endpoint is recorded in the plan.',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    accessModes: ['api_access'],
    accessLabel: 'API access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://dashboard.cohere.com/api-keys',
    officialSourceUrl: 'https://docs.cohere.com/reference/list-models',
    discoveryStrategy: 'official_provider_models',
    status: 'active_configurable',
    classification: 'active_configurable',
    liveCallable: true,
    fallbackModels: [],
    registryInclusionNote: 'Broad registry row; no current direct ProviderID mapping.',
    evidenceNote: 'Official Cohere model-list endpoint is provider-specific.',
  },
  {
    id: 'xai',
    name: 'xAI',
    accessModes: ['api_access', 'gateway_virtual_key'],
    accessLabel: 'API access or local gateway virtual-key access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://console.x.ai',
    officialSourceUrl: 'https://docs.x.ai/developers/rest-api-reference/inference/models',
    discoveryStrategy: 'openai_compatible_models',
    status: 'active_configurable',
    classification: 'gateway_configurable_openai_compatible',
    liveCallable: true,
    gatewayProfile: {
      kind: 'openai_compatible',
      defaultBaseUrl: 'https://api.x.ai/v1',
      note: 'Registry-only OpenAI-compatible row until a direct executable adapter is added.',
    },
    fallbackModels: [],
    registryInclusionNote: 'Broad registry row; no current direct ProviderID mapping.',
    evidenceNote: 'Official xAI models endpoint is recorded in the plan.',
  },
  {
    id: 'aws_bedrock',
    name: 'AWS Bedrock',
    accessModes: ['cloud_project'],
    accessLabel: 'Cloud project access',
    authLabel: 'AWS account, region, and IAM-authenticated environment',
    setupUrl: 'https://aws.amazon.com/bedrock/',
    officialSourceUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    discoveryStrategy: 'cloud_project_scoped_models',
    status: 'active_configurable',
    classification: 'cloud_project_required',
    liveCallable: true,
    fallbackModels: [],
    registryInclusionNote: 'Broad registry row; no current direct ProviderID mapping.',
    evidenceNote: 'Model availability is account, region, and project scoped.',
  },
  {
    id: 'azure_openai',
    name: 'Azure OpenAI',
    accessModes: ['cloud_project'],
    accessLabel: 'Cloud resource access',
    authLabel: 'Azure resource, deployment, region, and secret reference',
    setupUrl: 'https://learn.microsoft.com/azure/ai-services/openai/',
    officialSourceUrl: 'https://learn.microsoft.com/en-sg/azure/ai-services/openai/how-to/working-with-models',
    discoveryStrategy: 'cloud_project_scoped_models',
    status: 'active_configurable',
    classification: 'cloud_project_required',
    liveCallable: true,
    fallbackModels: [],
    registryInclusionNote: 'Broad registry row; no current direct ProviderID mapping.',
    evidenceNote: 'Model availability is resource/deployment scoped.',
  },
  {
    id: 'google_vertex_ai',
    name: 'Google Vertex AI',
    accessModes: ['cloud_project'],
    accessLabel: 'Cloud project access',
    authLabel: 'Google Cloud project, region, and application credentials',
    setupUrl: 'https://cloud.google.com/vertex-ai',
    officialSourceUrl: 'https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/inference',
    discoveryStrategy: 'cloud_project_scoped_models',
    status: 'active_configurable',
    classification: 'cloud_project_required',
    liveCallable: true,
    fallbackModels: [],
    registryInclusionNote: 'Broad registry row; no current direct ProviderID mapping.',
    evidenceNote: 'Model availability is project and region scoped.',
  },
  {
    id: 'together_ai',
    name: 'Together AI',
    accessModes: ['api_access', 'gateway_virtual_key'],
    accessLabel: 'API access or local gateway virtual-key access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://api.together.ai/settings/api-keys',
    officialSourceUrl: 'https://docs.together.ai/reference/models',
    discoveryStrategy: 'openai_compatible_models',
    status: 'active_configurable',
    classification: 'gateway_configurable_openai_compatible',
    liveCallable: true,
    gatewayProfile: {
      kind: 'openai_compatible',
      defaultBaseUrl: 'https://api.together.xyz/v1',
      note: 'Registry-only OpenAI-compatible row until a direct executable adapter is added.',
    },
    fallbackModels: [],
    registryInclusionNote: 'Broad registry row; no current direct ProviderID mapping.',
    evidenceNote: 'Official model-list reference is recorded in the plan.',
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    accessModes: ['api_access', 'gateway_virtual_key'],
    accessLabel: 'API access or endpoint-verified gateway access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://fireworks.ai/account/api-keys',
    officialSourceUrl: 'https://fireworks.ai/docs/api-reference/list-models',
    discoveryStrategy: 'account_scoped_models',
    status: 'active_configurable',
    classification: 'active_configurable',
    liveCallable: true,
    gatewayProfile: {
      kind: 'openai_compatible',
      note: 'Gateway-compatible only after the user-configured endpoint is verified.',
    },
    fallbackModels: [],
    registryInclusionNote: 'Broad registry row; no current direct ProviderID mapping.',
    evidenceNote: 'Official listing is account-scoped and must not be treated as universal static catalog.',
  },
  {
    id: 'replicate',
    name: 'Replicate',
    accessModes: ['api_access'],
    accessLabel: 'API access',
    authLabel: 'Environment variable API token reference',
    setupUrl: 'https://replicate.com/account/api-tokens',
    officialSourceUrl: 'https://replicate.com/docs/reference/http',
    discoveryStrategy: 'official_provider_models',
    status: 'active_configurable',
    classification: 'active_configurable',
    liveCallable: true,
    fallbackModels: [],
    registryInclusionNote: 'Broad registry row; no current direct ProviderID mapping.',
    evidenceNote: 'Replicate model discovery is provider-specific and not an OpenAI-compatible /v1/models contract.',
  },
  {
    id: 'nvidia_nim',
    name: 'NVIDIA NIM',
    accessModes: ['local_runtime', 'custom_openai_compatible'],
    accessLabel: 'Local/container runtime endpoint',
    authLabel: 'User-supplied local/container endpoint and optional secret reference',
    setupUrl: 'https://docs.nvidia.com/nim/',
    officialSourceUrl: 'https://docs.nvidia.com/nim/large-language-models/latest/reference/api-reference.html',
    discoveryStrategy: 'local_runtime_models',
    status: 'status_only',
    classification: 'local_runtime',
    liveCallable: true,
    gatewayProfile: {
      kind: 'openai_compatible',
      requiresUserEndpoint: true,
      note: 'Only local/container endpoints are implementation-safe in this row; managed variants require source review.',
    },
    fallbackModels: [],
    registryInclusionNote: 'Broad registry row; no current direct ProviderID mapping.',
    evidenceNote: 'Local/container NIM exposes OpenAI-compatible LLM endpoints; managed/ambiguous variants remain out of scope.',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    accessModes: ['api_access'],
    accessLabel: 'API access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://docs.perplexity.ai',
    officialSourceUrl: 'https://docs.perplexity.ai',
    discoveryStrategy: 'source_backed_static_models',
    status: 'active_configurable',
    classification: 'active_configurable',
    liveCallable: false,
    fallbackModels: ['perplexity/sonar'],
    registryInclusionNote: 'Source-backed model/pricing catalog row; execution remains gated until provider API semantics are tested.',
    evidenceNote: 'Official Perplexity docs expose model/pricing information, but Phase 4 does not invent a live model-list endpoint.',
  },
  {
    id: 'deepinfra',
    name: 'DeepInfra',
    accessModes: ['api_access', 'gateway_virtual_key'],
    accessLabel: 'API access or local gateway virtual-key access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://deepinfra.com/dash/api_keys',
    officialSourceUrl: 'https://deepinfra.mintlify.app/api-reference/models/models-list',
    discoveryStrategy: 'official_provider_models',
    status: 'active_configurable',
    classification: 'gateway_configurable_openai_compatible',
    liveCallable: true,
    gatewayProfile: {
      kind: 'openai_compatible',
      defaultBaseUrl: 'https://api.deepinfra.com/v1/openai',
      note: 'OpenAI-compatible execution may use the DeepInfra base URL; model discovery uses DeepInfra-specific models-list normalization.',
    },
    fallbackModels: [],
    registryInclusionNote: 'Broad registry row; execution is through a generic OpenAI-compatible target, not a new ProviderID.',
    evidenceNote: 'Official DeepInfra models-list endpoint is provider-specific and not generic /v1/models.',
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    accessModes: ['api_access', 'gateway_virtual_key'],
    accessLabel: 'API access or local gateway virtual-key access',
    authLabel: 'Environment variable API key reference',
    setupUrl: 'https://cloud.cerebras.ai',
    officialSourceUrl: 'https://inference-docs.cerebras.ai',
    discoveryStrategy: 'openai_compatible_models',
    status: 'active_configurable',
    classification: 'gateway_configurable_openai_compatible',
    liveCallable: true,
    gatewayProfile: {
      kind: 'openai_compatible',
      defaultBaseUrl: 'https://api.cerebras.ai/v1',
      note: 'Registry-only OpenAI-compatible row until a direct executable adapter is added.',
    },
    fallbackModels: [],
    registryInclusionNote: 'Broad registry row; no current direct ProviderID mapping.',
    evidenceNote: 'Classified as active and OpenAI-compatible by the approved T903 contract.',
  },
  {
    id: 'custom_openai_compatible',
    name: 'Custom OpenAI-Compatible Endpoint',
    accessModes: ['custom_openai_compatible', 'gateway_virtual_key'],
    accessLabel: 'Custom endpoint access',
    authLabel: 'User-supplied base URL plus env or gateway secret reference',
    setupUrl: 'https://platform.openai.com/docs/api-reference/introduction',
    officialSourceUrl: 'https://platform.openai.com/docs/api-reference/introduction',
    discoveryStrategy: 'manual_custom_models',
    status: 'active_configurable',
    classification: 'custom_openai_compatible',
    liveCallable: true,
    gatewayProfile: {
      kind: 'openai_compatible',
      requiresUserEndpoint: true,
      note: 'Model discovery is optional and must be probed from the configured endpoint, not assumed.',
    },
    fallbackModels: [],
    registryInclusionNote: 'Custom endpoint row; no current direct ProviderID mapping.',
    evidenceNote: 'User configuration supplies the endpoint contract, so manual models are the safe default.',
  },
]

export function getProviderRegistryEntry(id: ProviderRegistryID): ProviderRegistryEntry | undefined {
  return PROVIDER_REGISTRY.find((entry) => entry.id === id)
}

export function providerRegistryIdForExecutableProvider(provider: ProviderID): ProviderRegistryID {
  if (provider === 'claude-code') return 'claude_code'
  if (provider === 'codex') return 'openai_codex'
  return provider
}

export function providerAccessModeForAuthMode(authMode: LLMAuthMode): ProviderAccessMode {
  if (authMode === 'env_key') return 'api_access'
  if (authMode === 'gateway_virtual_key') return 'gateway_virtual_key'
  if (authMode === 'local_cli_session') return 'local_tool_session'
  return 'local_runtime'
}

export function isAuthModeAllowedForProvider(
  entry: ProviderRegistryEntry,
  authMode: LLMAuthMode
): boolean {
  if (authMode === 'env_key' && entry.accessModes.includes('custom_openai_compatible')) {
    return true
  }
  return entry.accessModes.includes(providerAccessModeForAuthMode(authMode))
}

export function assertAuthModeAllowedForProvider(
  entry: ProviderRegistryEntry,
  authMode: LLMAuthMode
): void {
  if (isAuthModeAllowedForProvider(entry, authMode)) return
  throw new Error(
    `${authMode} auth is not allowed for ${entry.name}. Allowed access modes: ${entry.accessModes.join(', ')}.`
  )
}

export function getPlannedSourceReviewProviderRows(): ProviderRegistryEntry[] {
  return PROVIDER_REGISTRY.filter((entry) => entry.discoveryStrategy === 'planned_provider_source_review')
}

export function getLiveCallableProviderRows(): ProviderRegistryEntry[] {
  return PROVIDER_REGISTRY.filter((entry) => entry.liveCallable)
}
